name: Deploying multiple runners
on: workflow_dispatch

jobs:
  clone-website-and-run-podman: 
    runs-on: ubuntu-latest

    steps: 
      - name: Git Clone repo
        run: git clone https://github.com/nikkitagora/website
      - name: move web files
        run: sudo mv ./website/* /usr/share/nginx/html/
      - name: Start Nginx Service
        run: sudo systemctl start nginx
      - name: Test Web Service
        run: python3 -c "import requests; r=requests.get('http://localhost:80'); print(r.status_code)"
  
  testing-api-availability:
    runs-on: ubuntu-latest
    steps:
      - name: ping the service
        run: ping 8.8.8.8 -n 50